#! /bin/bash

TMPFILE=/tmp/envloaderenv.tmp

clean () {
    if [ -f $TMPFILE ]; then
        rm $TMPFILE;
    fi;
}

clean;

python -m EnvironLoader $*;

if [ -f $TMPFILE ]; then
    if [ "$1" = "load" ]; then
        source $TMPFILE;
    fi
fi